--1
SELECT NAME
FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA';

--2
SELECT * FROM CITY

--3
SELECT * 
FROM CITY
WHERE ID = 1661

--4
SELECT * 
FROM CITY
WHERE ID = 1661

--5
SELECT NAME 
FROM CITY
WHERE COUNTRYCODE = 'JPN'

--6
SELECT CITY, STATE
FROM STATION

--7
SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

--8
SELECT COUNT(*) - COUNT(DISTINCT CITY) AS 'Difference'
FROM STATION

--9
SELECT CITY, CHAR_LENGTH(CITY) AS 'shortest CITY name'
FROM STATION
ORDER BY CHAR_LENGTH(CITY), CITY
LIMIT 1;

SELECT CITY, CHAR_LENGTH(CITY) 'longest CITY name'
FROM STATION
ORDER BY CHAR_LENGTH(CITY) DESC, CITY
LIMIT 1;

--10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'A%' 
    OR CITY LIKE 'E%' 
    OR CITY LIKE 'I%' 
    OR CITY LIKE 'U%'
    OR CITY LIKE 'O%'

--11
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%A'
OR CITY LIKE '%E'
OR CITY LIKE '%I'
OR CITY LIKE '%O'
OR CITY LIKE '%U'

--12
SELECT DISTINCT CITY
FROM STATION
WHERE (CITY LIKE 'E%'
    OR CITY LIKE 'O%'
    OR CITY LIKE 'A%'
    OR CITY LIKE 'U%'
    OR CITY LIKE 'I%')
AND (CITY LIKE '%E'
    OR CITY LIKE '%O'
    OR CITY LIKE '%A'
    OR CITY LIKE '%U'
    OR CITY LIKE '%I')

--13
SELECT DISTINCT CITY
FROM STATION
WHERE  CITY NOT LIKE 'A%' 
    OR CITY NOT LIKE 'E%' 
    OR CITY NOT LIKE 'I%' 
    OR CITY NOT LIKE 'U%'
    OR CITY NOT LIKE 'O%'

--14
SELECT DISTINCT CITY
FROM STATION
WHERE  CITY NOT LIKE 'A%' 
    AND CITY NOT LIKE 'E%' 
    AND CITY NOT LIKE 'I%' 
    AND CITY NOT LIKE 'U%'
    AND CITY NOT LIKE 'O%'

--15
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE '%A'
AND CITY NOT LIKE '%E'
AND CITY NOT LIKE '%I'
AND CITY NOT LIKE '%O'
AND CITY NOT LIKE '%U'

--16
SELECT DISTINCT CITY
FROM STATION
WHERE (CITY NOT LIKE 'E%'
    AND CITY NOT LIKE 'O%'
    AND CITY NOT LIKE 'A%'
    AND CITY NOT LIKE 'U%'
    AND CITY NOT LIKE 'I%')
OR (CITY NOT LIKE '%E'
    AND CITY NOT LIKE '%O'
    AND CITY NOT LIKE '%A'
    AND CITY NOT LIKE '%U'
    AND CITY NOT LIKE '%I')
